// The test hillside, made on the spot.
//
//   The suite needs ground, and it must not need the atlas: a test that goes red because a deploy
//   is mid-flight has told you nothing. So it gets its own — a tilted plane whose height at any
//   point is arithmetic, encoded exactly the way the atlas encodes USGS 3DEP, and generated here
//   rather than committed. No binaries in the repo, nothing to regenerate, and every assertion in
//   the suite can be checked against a number rather than against whatever the renderer produced.
//
//     h(lng, lat) = BASE + SLOPE_EAST * metres_east + SLOPE_NORTH * metres_north
//
//   Flat enough to walk, steep enough that following it is visibly different from walking on a
//   horizontal plane.

import { deflateSync } from 'zlib';

export const SIZE = 256;
export const Z = 17;
export const ORIGIN = { lng: -119.156345, lat: 34.432675 };
export const SURFACE = { base: 500, east: 0.05, north: -0.03 };
export const PAD = 0.0022;

const R = 6378137, D2R = Math.PI / 180;
const MX = R * Math.cos(ORIGIN.lat * D2R) * D2R;
const MY = R * D2R;

/** the surface itself — the one number every assertion in the suite is checked against */
export const height = (lng, lat) =>
  SURFACE.base + SURFACE.east * (lng - ORIGIN.lng) * MX + SURFACE.north * (lat - ORIGIN.lat) * MY;

export const bbox = () => [ORIGIN.lng - PAD, ORIGIN.lat - PAD, ORIGIN.lng + PAD, ORIGIN.lat + PAD];

export function tileOf(lng, lat, z) {
  const n = 2 ** z;
  const latR = lat * D2R;
  return {
    x: Math.floor(((lng + 180) / 360) * n),
    y: Math.floor(((1 - Math.log(Math.tan(latR) + 1 / Math.cos(latR)) / Math.PI) / 2) * n)
  };
}

export function tileBounds(x, y, z) {
  const n = 2 ** z;
  const lng = i => (i / n) * 360 - 180;
  const lat = j => {
    const s = Math.PI * (1 - (2 * j) / n);
    return (180 / Math.PI) * Math.atan(0.5 * (Math.exp(s) - Math.exp(-s)));
  };
  return { w: lng(x), s: lat(y + 1), e: lng(x + 1), n: lat(y) };
}

/** every tile of the fixture area, so the server knows what it is allowed to answer */
export function tiles() {
  const b = bbox();
  const a = tileOf(b[0], b[3], Z), c = tileOf(b[2], b[1], Z);
  const out = [];
  for (let x = a.x; x <= c.x; x++) for (let y = a.y; y <= c.y; y++) out.push({ z: Z, x, y });
  return out;
}

export function index() {
  return {
    schema: 1,
    note: 'Synthetic tilted plane, generated by the test suite. Not real elevation.',
    encoding: 'terrarium', tileSize: SIZE, minzoom: Z, maxzoom: Z,
    surface: { ...SURFACE, origin: [ORIGIN.lng, ORIGIN.lat] },
    areas: [{ pid: 'fixture', bbox: bbox(), tiles: tiles().length }]
  };
}

// ---- a very small PNG writer -------------------------------------------------------------------
// Only what a terrarium tile needs: 8-bit RGB, no interlacing, one filter byte per row. Writing it
// here rather than pulling in an image library keeps the suite dependency-free.

const CRC = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}

function png(width, height_, rgb) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height_, 4);
  ihdr[8] = 8;        // bit depth
  ihdr[9] = 2;        // colour type: truecolour
  const raw = Buffer.alloc(height_ * (1 + width * 3));
  for (let y = 0; y < height_; y++) {
    const row = y * (1 + width * 3);
    raw[row] = 0;     // filter: none
    rgb.copy(raw, row + 1, y * width * 3, (y + 1) * width * 3);
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 6 })),
    chunk('IEND', Buffer.alloc(0))
  ]);
}

/** one terrarium tile of the fixture surface */
export function tilePng(z, x, y) {
  const b = tileBounds(x, y, z);
  const rgb = Buffer.alloc(SIZE * SIZE * 3);
  let k = 0;
  for (let j = 0; j < SIZE; j++) {
    const lat = b.n - ((j + 0.5) / SIZE) * (b.n - b.s);
    for (let i = 0; i < SIZE; i++) {
      const lng = b.w + ((i + 0.5) / SIZE) * (b.e - b.w);
      const v = Math.min(32767, Math.max(-32768, height(lng, lat))) + 32768;
      const r = Math.floor(v / 256);
      const g = Math.floor(v - r * 256);
      const bl = Math.floor((v - Math.floor(v)) * 256);
      rgb[k++] = r; rgb[k++] = g; rgb[k++] = bl;
    }
  }
  return png(SIZE, SIZE, rgb);
}

// ---- a data pack for the same hillside ------------------------------------------------------------
// The pack is the property's record: the surveyed line, what stands, every tree, the road, the
// placed zones. Like the terrain it is generated, not committed, and every position below is
// metres east and north of the origin so the assertions can be worked out by hand.

/** metres east/north of the origin -> lng/lat */
export const at = (e, n) => [ORIGIN.lng + e / MX, ORIGIN.lat + n / MY];
const box = (e0, n0, e1, n1) => [at(e0, n0), at(e1, n0), at(e1, n1), at(e0, n1), at(e0, n0)];

/** forty trees in the east of the area, in five rows, none of them on a footprint or the spawn */
export const PACK_TREES = [];
for (const e of [50, 60, 70, 80, 90]) {
  for (const n of [-80, -60, -40, -20, 0, 20, 40, 60]) {
    const height = 4 + ((e / 10 + n / 20 + 12) % 9) * 2;      // 4..20 m, deterministic
    PACK_TREES.push({ e, n, height, crown: 1.5 + (height % 5) });
  }
}

export const PACK_FRAME = { origin_lng: ORIGIN.lng - 150 / MX, origin_lat: ORIGIN.lat - 150 / MY, metres_per_deg_lng: MX, metres_per_deg_lat: MY };
export const PACK_AOI = [at(-100, -100)[0], at(-100, -100)[1], at(100, 100)[0], at(100, 100)[1]];
export const PACK_HOUSE = { e0: 35, n0: 26, e1: 45, n1: 34, roof: 3.6 };
export const PACK_GARAGE = { e0: -46, n0: 25, e1: -34, n1: 35, roof: 4.0 };
export const PACK_PAD = { e0: 37, n0: 42, e1: 43, n1: 48 };

export function packFiles(base) {
  const f = PACK_FRAME;
  const rows = PACK_TREES.map(t => {
    const x = Math.round((t.e + 150) * 10), y = Math.round((t.n + 150) * 10);
    return `${x},${y},${Math.round(t.height * 10)},${Math.round(t.crown * 10)},${Math.round(height(...at(t.e, t.n)) * 10)}`;
  });
  const fc = features => ({ type: 'FeatureCollection', features });
  const poly = (props, ring) => ({ type: 'Feature', properties: props, geometry: { type: 'Polygon', coordinates: [ring] } });
  const line = (props, pts) => ({ type: 'Feature', properties: props, geometry: { type: 'LineString', coordinates: pts } });
  const point = (props, p) => ({ type: 'Feature', properties: props, geometry: { type: 'Point', coordinates: p } });
  return {
    'pack.json': {
      schema: 1, id: 'fixture-pack', name: 'Fixture Hill', frame: f,
      aoi: { bbox: PACK_AOI }, spawn: { lng: ORIGIN.lng, lat: ORIGIN.lat, heading: 0 },
      layers: {
        survey: { file: 'survey.geojson', authority: 'survey', date: '2024-11-14' },
        county: { file: 'county.geojson', authority: 'county' },
        roofs: { file: 'roofs.geojson', authority: 'derived', captured: '2018' },
        trees: { file: 'trees.csv', authority: 'derived', captured: '2018', columns: ['x_east_dm', 'y_north_dm', 'height_dm', 'crown_radius_dm', 'ground_dm'] },
        vision: { file: 'vision.geojson', authority: 'proposal' },
        imagery: { kind: 'xyz', template: `${base}/aerial/{z}/{y}/{x}`, maxzoom: 18, captured: '2025' }
      }
    },
    'trees.csv': 'x_east_dm,y_north_dm,height_dm,crown_radius_dm,ground_dm\n' + rows.join('\n') + '\n',
    'survey.geojson': fc([
      poly({ layer: 'boundary', authority: 'survey' }, box(-80, -80, 80, 80)),
      poly({ layer: 'easement', authority: 'survey' }, box(-80, -80, -76, 80)),
      point({ layer: 'monument', authority: 'survey', label: 'fixture pipe' }, at(80, 80))
    ]),
    'county.geojson': fc([
      poly({ layer: 'parcel', authority: 'county' }, box(-90, -90, 90, 90)),
      poly({ layer: 'footprint', authority: 'county', lidar_2018: { kind: 'house', roof_m: 3.6, roof_p50_m: PACK_HOUSE.roof } }, box(PACK_HOUSE.e0, PACK_HOUSE.n0, PACK_HOUSE.e1, PACK_HOUSE.n1)),
      poly({ layer: 'footprint', authority: 'county', lidar_2018: { kind: 'concrete pad', roof_m: null } }, box(PACK_PAD.e0, PACK_PAD.n0, PACK_PAD.e1, PACK_PAD.n1)),
      line({ layer: 'road', authority: 'county', name: 'FIXTURE RD' }, [at(-90, -20), at(0, -20), at(90, -20)])
    ]),
    'roofs.geojson': fc([
      poly({ layer: 'roof', authority: 'derived', kind: 'warehouse', roof_m: PACK_GARAGE.roof, county_footprint: null }, box(PACK_GARAGE.e0, PACK_GARAGE.n0, PACK_GARAGE.e1, PACK_GARAGE.n1))
    ]),
    'vision.geojson': fc([
      point({ id: 'the-barn', name: 'The Barn', mode: 'both', placeholder: true }, at(-60, -40)),
      point({ id: 'retreat', name: 'Retreat Village', mode: 'vision', placeholder: true }, at(60, -40)),
      point({ id: 'hub', name: 'Community Hub', mode: 'vision', placeholder: true }, at(0, 70))
    ])
  };
}

/** an aerial tile: one flat colour with a darker rim, so a draped ring is visibly a photograph and not the slope shading */
export function aerialPng(z, x, y) {
  const rgb = Buffer.alloc(SIZE * SIZE * 3);
  const shade = 96 + ((x * 7 + y * 13) % 5) * 8;
  for (let j = 0; j < SIZE; j++) {
    for (let i = 0; i < SIZE; i++) {
      const k = (j * SIZE + i) * 3;
      const rim = i < 2 || j < 2 || i >= SIZE - 2 || j >= SIZE - 2;
      rgb[k] = rim ? 40 : shade; rgb[k + 1] = rim ? 40 : shade + 24; rgb[k + 2] = rim ? 40 : 70;
    }
  }
  return png(SIZE, SIZE, rgb);
}
