// The test hillside, made on the spot.
//
//   The suite needs ground, and it must not need the atlas: a test that goes red because a deploy
//   is mid-flight has told you nothing. So it gets its own — a tilted plane whose height at any
//   point is arithmetic, encoded exactly the way the atlas encodes USGS 3DEP, and generated here
//   rather than committed. No binaries in the repo, nothing to regenerate, and every assertion in
//   the suite can be checked against a number rather than against whatever the renderer produced.
//
//     h(lng, lat) = BASE + SLOPE_EAST * metres_east + SLOPE_NORTH * metres_north
//
//   Flat enough to walk, steep enough that following it is visibly different from walking on a
//   horizontal plane.

import { deflateSync } from 'zlib';

export const SIZE = 256;
export const Z = 17;
export const ORIGIN = { lng: -119.156345, lat: 34.432675 };
export const SURFACE = { base: 500, east: 0.05, north: -0.03 };
export const PAD = 0.0022;

const R = 6378137, D2R = Math.PI / 180;
const MX = R * Math.cos(ORIGIN.lat * D2R) * D2R;
const MY = R * D2R;

/** the surface itself — the one number every assertion in the suite is checked against */
export const height = (lng, lat) =>
  SURFACE.base + SURFACE.east * (lng - ORIGIN.lng) * MX + SURFACE.north * (lat - ORIGIN.lat) * MY;

export const bbox = () => [ORIGIN.lng - PAD, ORIGIN.lat - PAD, ORIGIN.lng + PAD, ORIGIN.lat + PAD];

export function tileOf(lng, lat, z) {
  const n = 2 ** z;
  const latR = lat * D2R;
  return {
    x: Math.floor(((lng + 180) / 360) * n),
    y: Math.floor(((1 - Math.log(Math.tan(latR) + 1 / Math.cos(latR)) / Math.PI) / 2) * n)
  };
}

export function tileBounds(x, y, z) {
  const n = 2 ** z;
  const lng = i => (i / n) * 360 - 180;
  const lat = j => {
    const s = Math.PI * (1 - (2 * j) / n);
    return (180 / Math.PI) * Math.atan(0.5 * (Math.exp(s) - Math.exp(-s)));
  };
  return { w: lng(x), s: lat(y + 1), e: lng(x + 1), n: lat(y) };
}

/** every tile of the fixture area, so the server knows what it is allowed to answer */
export function tiles() {
  const b = bbox();
  const a = tileOf(b[0], b[3], Z), c = tileOf(b[2], b[1], Z);
  const out = [];
  for (let x = a.x; x <= c.x; x++) for (let y = a.y; y <= c.y; y++) out.push({ z: Z, x, y });
  return out;
}

export function index() {
  return {
    schema: 1,
    note: 'Synthetic tilted plane, generated by the test suite. Not real elevation.',
    encoding: 'terrarium', tileSize: SIZE, minzoom: Z, maxzoom: Z,
    surface: { ...SURFACE, origin: [ORIGIN.lng, ORIGIN.lat] },
    areas: [{ pid: 'fixture', bbox: bbox(), tiles: tiles().length }]
  };
}

// ---- a very small PNG writer -------------------------------------------------------------------
// Only what a terrarium tile needs: 8-bit RGB, no interlacing, one filter byte per row. Writing it
// here rather than pulling in an image library keeps the suite dependency-free.

const CRC = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}

function png(width, height_, rgb) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height_, 4);
  ihdr[8] = 8;        // bit depth
  ihdr[9] = 2;        // colour type: truecolour
  const raw = Buffer.alloc(height_ * (1 + width * 3));
  for (let y = 0; y < height_; y++) {
    const row = y * (1 + width * 3);
    raw[row] = 0;     // filter: none
    rgb.copy(raw, row + 1, y * width * 3, (y + 1) * width * 3);
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 6 })),
    chunk('IEND', Buffer.alloc(0))
  ]);
}

/** one terrarium tile of the fixture surface */
export function tilePng(z, x, y) {
  const b = tileBounds(x, y, z);
  const rgb = Buffer.alloc(SIZE * SIZE * 3);
  let k = 0;
  for (let j = 0; j < SIZE; j++) {
    const lat = b.n - ((j + 0.5) / SIZE) * (b.n - b.s);
    for (let i = 0; i < SIZE; i++) {
      const lng = b.w + ((i + 0.5) / SIZE) * (b.e - b.w);
      const v = Math.min(32767, Math.max(-32768, height(lng, lat))) + 32768;
      const r = Math.floor(v / 256);
      const g = Math.floor(v - r * 256);
      const bl = Math.floor((v - Math.floor(v)) * 256);
      rgb[k++] = r; rgb[k++] = g; rgb[k++] = bl;
    }
  }
  return png(SIZE, SIZE, rgb);
}

// ---- a data pack for the same hillside ------------------------------------------------------------
// The pack is the property's record: the surveyed line, what stands, every tree, the road, the
// placed zones. Like the terrain it is generated, not committed, and every position below is
// metres east and north of the origin so the assertions can be worked out by hand.

/** metres east/north of the origin -> lng/lat */
export const at = (e, n) => [ORIGIN.lng + e / MX, ORIGIN.lat + n / MY];
const box = (e0, n0, e1, n1) => [at(e0, n0), at(e1, n0), at(e1, n1), at(e0, n1), at(e0, n0)];

/** forty trees in the east of the area, in five rows, none of them on a footprint or the spawn */
export const PACK_TREES = [];
for (const e of [50, 60, 70, 80, 90]) {
  for (const n of [-80, -60, -40, -20, 0, 20, 40, 60]) {
    const height = 4 + ((e / 10 + n / 20 + 12) % 9) * 2;      // 4..20 m, deterministic
    PACK_TREES.push({ e, n, height, crown: 1.5 + (height % 5) });
  }
}

export const PACK_FRAME = { origin_lng: ORIGIN.lng - 150 / MX, origin_lat: ORIGIN.lat - 150 / MY, metres_per_deg_lng: MX, metres_per_deg_lat: MY };
export const PACK_AOI = [at(-100, -100)[0], at(-100, -100)[1], at(100, 100)[0], at(100, 100)[1]];
export const PACK_HOUSE = { e0: 35, n0: 26, e1: 45, n1: 34, roof: 3.6 };
export const PACK_GARAGE = { e0: -46, n0: 25, e1: -34, n1: 35, roof: 4.0 };
export const PACK_PAD = { e0: 37, n0: 42, e1: 43, n1: 48 };

// the owner's edits: everything within 12 m of the house is gone, and so is one tree at a point.
// (50,20) is 5 m from the house box and (50,40) is 7.8 m — both go; (60,20) at 15 m stays.
export const PACK_EDITS = { houseBuffer: 12, point: { e: 90, n: -80, r: 5 } };
const boxDistance = (e, n, b) => Math.hypot(Math.max(b.e0 - e, 0, e - b.e1), Math.max(b.n0 - n, 0, n - b.n1));
export const removedByEdits = t =>
  boxDistance(t.e, t.n, PACK_HOUSE) <= PACK_EDITS.houseBuffer ||
  Math.hypot(t.e - PACK_EDITS.point.e, t.n - PACK_EDITS.point.n) <= PACK_EDITS.point.r;
/** the trees as they stand once the edits are applied */
export const PACK_STANDING = PACK_TREES.filter(t => !removedByEdits(t));

export function packFiles(base) {
  const f = PACK_FRAME;
  const rows = PACK_TREES.map(t => {
    const x = Math.round((t.e + 150) * 10), y = Math.round((t.n + 150) * 10);
    return `${x},${y},${Math.round(t.height * 10)},${Math.round(t.crown * 10)},${Math.round(height(...at(t.e, t.n)) * 10)}`;
  });
  const fc = features => ({ type: 'FeatureCollection', features });
  const poly = (props, ring) => ({ type: 'Feature', properties: props, geometry: { type: 'Polygon', coordinates: [ring] } });
  const line = (props, pts) => ({ type: 'Feature', properties: props, geometry: { type: 'LineString', coordinates: pts } });
  const point = (props, p) => ({ type: 'Feature', properties: props, geometry: { type: 'Point', coordinates: p } });
  return {
    'pack.json': {
      schema: 1, id: 'fixture-pack', name: 'Fixture Hill', frame: f,
      aoi: { bbox: PACK_AOI }, spawn: { lng: ORIGIN.lng, lat: ORIGIN.lat, heading: 0 },
      layers: {
        survey: { file: 'survey.geojson', authority: 'survey', date: '2024-11-14' },
        county: { file: 'county.geojson', authority: 'county' },
        roofs: { file: 'roofs.geojson', authority: 'derived', captured: '2018' },
        trees: { file: 'trees.csv', authority: 'derived', captured: '2018', columns: ['x_east_dm', 'y_north_dm', 'height_dm', 'crown_radius_dm', 'ground_dm'] },
        vision: { file: 'vision.geojson', authority: 'proposal' },
        edits: { file: 'edits.geojson', authority: 'owner' },
        materials: { file: 'materials.json', authority: 'derived' },
        imagery: { kind: 'xyz', template: `${base}/aerial/{z}/{y}/{x}`, maxzoom: 18, captured: '2025' }
      }
    },
    'materials.json': materialsJson(base),
    'edits.geojson': fc([
      poly({ id: 'trees-around-the-house', op: 'remove', layer: 'trees', buffer_m: PACK_EDITS.houseBuffer, by: 'owner', reported: '2026-09-18' }, box(PACK_HOUSE.e0, PACK_HOUSE.n0, PACK_HOUSE.e1, PACK_HOUSE.n1)),
      point({ id: 'one-tree', op: 'remove', layer: 'trees', radius_m: PACK_EDITS.point.r, by: 'owner' }, at(PACK_EDITS.point.e, PACK_EDITS.point.n)),
      point({ id: 'not-a-removal', op: 'note', layer: 'trees', radius_m: 500, by: 'owner' }, at(0, 0))
    ]),
    'trees.csv': 'x_east_dm,y_north_dm,height_dm,crown_radius_dm,ground_dm\n' + rows.join('\n') + '\n',
    'survey.geojson': fc([
      poly({ layer: 'boundary', authority: 'survey' }, box(-80, -80, 80, 80)),
      poly({ layer: 'easement', authority: 'survey' }, box(-80, -80, -76, 80)),
      point({ layer: 'monument', authority: 'survey', label: 'fixture pipe' }, at(80, 80))
    ]),
    'county.geojson': fc([
      poly({ layer: 'parcel', authority: 'county' }, box(-90, -90, 90, 90)),
      poly({ layer: 'footprint', authority: 'county', lidar_2018: { kind: 'house', roof_m: 3.6, roof_p50_m: PACK_HOUSE.roof } }, box(PACK_HOUSE.e0, PACK_HOUSE.n0, PACK_HOUSE.e1, PACK_HOUSE.n1)),
      poly({ layer: 'footprint', authority: 'county', lidar_2018: { kind: 'concrete pad', roof_m: null } }, box(PACK_PAD.e0, PACK_PAD.n0, PACK_PAD.e1, PACK_PAD.n1)),
      line({ layer: 'road', authority: 'county', name: 'FIXTURE RD' }, [at(-90, -20), at(0, -20), at(90, -20)])
    ]),
    'roofs.geojson': fc([
      poly({ layer: 'roof', authority: 'derived', kind: 'warehouse', roof_m: PACK_GARAGE.roof, county_footprint: null }, box(PACK_GARAGE.e0, PACK_GARAGE.n0, PACK_GARAGE.e1, PACK_GARAGE.n1))
    ]),
    'vision.geojson': fc([
      point({ id: 'the-barn', name: 'The Barn', mode: 'both', placeholder: true }, at(-60, -40)),
      point({ id: 'retreat', name: 'Retreat Village', mode: 'vision', placeholder: true }, at(60, -40)),
      point({ id: 'hub', name: 'Community Hub', mode: 'vision', placeholder: true }, at(0, 70))
    ])
  };
}

/**
 * An aerial tile of the fixture land, painted rather than photographed: dry straw everywhere, the
 * road as a grey strip, the concrete pad pale, and a dark green disc of canopy over every tree in
 * the pack. It is what a photograph of this hillside would show, so the grain has something real
 * to read — straw where it is gold, gravel where it is grey, litter under the canopy.
 */
export function aerialPng(z, x, y) {
  const b = tileBounds(x, y, z);
  const rgb = Buffer.alloc(SIZE * SIZE * 3);
  const trees = PACK_TREES.map(t => ({ e: t.e, n: t.n, r: t.crown }));
  for (let j = 0; j < SIZE; j++) {
    const lat = b.n - ((j + 0.5) / SIZE) * (b.n - b.s);
    const n = (lat - ORIGIN.lat) * MY;
    for (let i = 0; i < SIZE; i++) {
      const lng = b.w + ((i + 0.5) / SIZE) * (b.e - b.w);
      const e = (lng - ORIGIN.lng) * MX;
      const k = (j * SIZE + i) * 3;
      const speck = ((i * 31 + j * 17) % 7) * 3;                       // a little grain in the photograph itself
      let r = 188 + speck, g = 168 + speck, bl = 133 + speck;          // straw, #bca885
      if (Math.abs(n + 20) <= 2.2) { r = 138; g = 136; bl = 134; }      // the road, grey
      if (e >= PACK_PAD.e0 && e <= PACK_PAD.e1 && n >= PACK_PAD.n0 && n <= PACK_PAD.n1) { r = 200; g = 196; bl = 188; }   // the pad, pale
      for (const t of trees) {
        if ((e - t.e) * (e - t.e) + (n - t.n) * (n - t.n) <= t.r * t.r) { r = 78; g = 107; bl = 63; break; }   // canopy, #4e6b3f
      }
      rgb[k] = r; rgb[k + 1] = g; rgb[k + 2] = bl;
    }
  }
  return png(SIZE, SIZE, rgb);
}

/**
 * A close-up tile: a flat colour with a fine checker, so its mean is known and its grain is visible.
 * The four ground tiles and the road's asphalt are all this, in five colours.
 */
export function tilePngFlat(name) {
  const base = { straw: [188, 168, 133], dirt: [205, 184, 151], gravel: [199, 184, 159], litter: [154, 138, 112], asphalt: [86, 82, 72] }[name] || [128, 128, 128];
  const rgb = Buffer.alloc(SIZE * SIZE * 3);
  for (let j = 0; j < SIZE; j++) {
    for (let i = 0; i < SIZE; i++) {
      const k = (j * SIZE + i) * 3;
      const d = ((i >> 3) + (j >> 3)) % 2 ? 12 : -12;
      rgb[k] = base[0] + d; rgb[k + 1] = base[1] + d; rgb[k + 2] = base[2] + d;
    }
  }
  return png(SIZE, SIZE, rgb);
}

/** the pack's materials manifest, pointing at the flat tiles the server paints */
export function materialsJson(base) {
  const m = {};
  for (const [name, metres] of [['straw', 1.6], ['dirt', 2.0], ['gravel', 1.2], ['litter', 1.5], ['asphalt', 3.0]]) {
    m[name] = { albedo: `${base}/tile/${name}.png`, albedo_512: `${base}/tile/${name}.png`, metres, source: { id: 'fixture' }, matched_to: null };
  }
  return { note: 'fixture materials', materials: m };
}

// ---- a model you can go into ------------------------------------------------------------------------
// A small house as a .glb, generated here like everything else: a slab 8 m by 6 m, a wall along its
// south edge, a roof on four posts, and `extras.walk` saying the slab is a floor and the wall is a
// wall. The world reads that and lets the walker in.
export const FIXTURE_MODEL = { w: 8, d: 6, slab: 0.4, wall: 3.0, roof: 3.7 };
/** how far north of the house the free-standing fire ring sits, in metres — see the comment at its box() */
const FIRE_RING_Z = 10;

export function fixtureModelGlb() {
  const { w, d, slab, wall, roof } = FIXTURE_MODEL;
  const pos = []; const idx = [];
  const box = (x0, y0, z0, x1, y1, z1) => {
    const b = pos.length / 3;
    const c = [[x0, y0, z0], [x1, y0, z0], [x1, y0, z1], [x0, y0, z1], [x0, y1, z0], [x1, y1, z0], [x1, y1, z1], [x0, y1, z1]];
    for (const p of c) pos.push(...p);
    // six faces, each two triangles, wound outward
    const f = [[0, 3, 2, 1], [4, 5, 6, 7], [0, 1, 5, 4], [1, 2, 6, 5], [2, 3, 7, 6], [3, 0, 4, 7]];
    for (const [a, bq, cq, dq] of f) idx.push(b + a, b + bq, b + cq, b + a, b + cq, b + dq);
  };
  box(-w / 2, 0, -d / 2, w / 2, slab, d / 2);                                 // the slab
  box(-w / 2, slab, d / 2 - 0.2, w / 2, slab + wall, d / 2);                  // the south wall (z = +d/2 is south)
  box(-w / 2, roof - 0.3, -d / 2, w / 2, roof, d / 2);                        // the roof
  for (const [x, z] of [[-w / 2 + 0.2, -d / 2 + 0.2], [w / 2 - 0.2, -d / 2 + 0.2]]) box(x - 0.1, slab, z - 0.1, x + 0.1, roof - 0.3, z + 0.1);
  //   A fire ring, standing on its own ten metres north of the house and DELIBERATELY outside the
  //   ground the registry outline clears. The Oak Leaf does exactly this — its fire ring, seating
  //   and standing stone sit in an oak lounge left uncleared so the recorded oaks there survive —
  //   and the engine used to leave them unprotected, because planting consulted outlines only.
  //   It has to be well clear of the outline's own 3.5 m pad, or the pad protects it by accident
  //   and the test that guards this proves nothing.
  box(-0.6, 0, -FIRE_RING_Z - 0.6, 0.6, 0.45, -FIRE_RING_Z + 0.6);
  const P = new Float32Array(pos); const I = new Uint32Array(idx);
  const min = [Infinity, Infinity, Infinity], max = [-Infinity, -Infinity, -Infinity];
  for (let i = 0; i < P.length; i += 3) for (let k = 0; k < 3; k++) { min[k] = Math.min(min[k], P[i + k]); max[k] = Math.max(max[k], P[i + k]); }
  const pad = n => (4 - (n % 4)) % 4;
  const pb = Buffer.from(P.buffer), ib = Buffer.from(I.buffer);
  const bin = Buffer.concat([pb, Buffer.alloc(pad(pb.length)), ib, Buffer.alloc(pad(ib.length))]);
  const walk = {
    floors: [{ name: 'slab', ring: [[-w / 2, -d / 2], [w / 2, -d / 2], [w / 2, d / 2], [-w / 2, d / 2]], top: slab }],
    solids: [
      { name: 'wall', ring: [[-w / 2, d / 2 - 0.2], [w / 2, d / 2 - 0.2], [w / 2, d / 2], [-w / 2, d / 2]], base: slab, top: slab + wall },
      { name: 'fire ring', ring: [[-0.6, -FIRE_RING_Z - 0.6], [0.6, -FIRE_RING_Z - 0.6], [0.6, -FIRE_RING_Z + 0.6], [-0.6, -FIRE_RING_Z + 0.6]], base: 0, top: 0.45 }
    ]
  };
  const doc = {
    asset: { version: '2.0', generator: 'spatial-map fixture' },
    scene: 0, scenes: [{ nodes: [0], extras: { walk } }],
    nodes: [{ name: 'fixture house', mesh: 0, extras: { walk } }],
    meshes: [{ primitives: [{ attributes: { POSITION: 0 }, indices: 1, material: 0 }] }],
    materials: [{ name: 'render', doubleSided: true, pbrMetallicRoughness: { baseColorFactor: [0.8, 0.75, 0.65, 1], metallicFactor: 0, roughnessFactor: 0.9 } }],
    accessors: [
      { bufferView: 0, componentType: 5126, count: P.length / 3, type: 'VEC3', min, max },
      { bufferView: 1, componentType: 5125, count: I.length, type: 'SCALAR' }
    ],
    bufferViews: [
      { buffer: 0, byteOffset: 0, byteLength: pb.length, target: 34962 },
      { buffer: 0, byteOffset: pb.length + pad(pb.length), byteLength: ib.length, target: 34963 }
    ],
    buffers: [{ byteLength: bin.length }]
  };
  let json = Buffer.from(JSON.stringify(doc));
  json = Buffer.concat([json, Buffer.alloc(pad(json.length), 0x20)]);
  const header = Buffer.alloc(12); header.writeUInt32LE(0x46546c67, 0); header.writeUInt32LE(2, 4); header.writeUInt32LE(12 + 8 + json.length + 8 + bin.length, 8);
  const jh = Buffer.alloc(8); jh.writeUInt32LE(json.length, 0); jh.writeUInt32LE(0x4e4f534a, 4);
  const bh = Buffer.alloc(8); bh.writeUInt32LE(bin.length, 0); bh.writeUInt32LE(0x004e4942, 4);
  return Buffer.concat([header, jh, json, bh, bin]);
}
