// The test hillside, made on the spot.
//
//   The suite needs ground, and it must not need the atlas: a test that goes red because a deploy
//   is mid-flight has told you nothing. So it gets its own — a tilted plane whose height at any
//   point is arithmetic, encoded exactly the way the atlas encodes USGS 3DEP, and generated here
//   rather than committed. No binaries in the repo, nothing to regenerate, and every assertion in
//   the suite can be checked against a number rather than against whatever the renderer produced.
//
//     h(lng, lat) = BASE + SLOPE_EAST * metres_east + SLOPE_NORTH * metres_north
//
//   Flat enough to walk, steep enough that following it is visibly different from walking on a
//   horizontal plane.

import { deflateSync } from 'zlib';

export const SIZE = 256;
export const Z = 17;
export const ORIGIN = { lng: -119.156345, lat: 34.432675 };
export const SURFACE = { base: 500, east: 0.05, north: -0.03 };
export const PAD = 0.0022;

const R = 6378137, D2R = Math.PI / 180;
const MX = R * Math.cos(ORIGIN.lat * D2R) * D2R;
const MY = R * D2R;

/** the surface itself — the one number every assertion in the suite is checked against */
export const height = (lng, lat) =>
  SURFACE.base + SURFACE.east * (lng - ORIGIN.lng) * MX + SURFACE.north * (lat - ORIGIN.lat) * MY;

export const bbox = () => [ORIGIN.lng - PAD, ORIGIN.lat - PAD, ORIGIN.lng + PAD, ORIGIN.lat + PAD];

export function tileOf(lng, lat, z) {
  const n = 2 ** z;
  const latR = lat * D2R;
  return {
    x: Math.floor(((lng + 180) / 360) * n),
    y: Math.floor(((1 - Math.log(Math.tan(latR) + 1 / Math.cos(latR)) / Math.PI) / 2) * n)
  };
}

export function tileBounds(x, y, z) {
  const n = 2 ** z;
  const lng = i => (i / n) * 360 - 180;
  const lat = j => {
    const s = Math.PI * (1 - (2 * j) / n);
    return (180 / Math.PI) * Math.atan(0.5 * (Math.exp(s) - Math.exp(-s)));
  };
  return { w: lng(x), s: lat(y + 1), e: lng(x + 1), n: lat(y) };
}

/** every tile of the fixture area, so the server knows what it is allowed to answer */
export function tiles() {
  const b = bbox();
  const a = tileOf(b[0], b[3], Z), c = tileOf(b[2], b[1], Z);
  const out = [];
  for (let x = a.x; x <= c.x; x++) for (let y = a.y; y <= c.y; y++) out.push({ z: Z, x, y });
  return out;
}

export function index() {
  return {
    schema: 1,
    note: 'Synthetic tilted plane, generated by the test suite. Not real elevation.',
    encoding: 'terrarium', tileSize: SIZE, minzoom: Z, maxzoom: Z,
    surface: { ...SURFACE, origin: [ORIGIN.lng, ORIGIN.lat] },
    areas: [{ pid: 'fixture', bbox: bbox(), tiles: tiles().length }]
  };
}

// ---- a very small PNG writer -------------------------------------------------------------------
// Only what a terrarium tile needs: 8-bit RGB, no interlacing, one filter byte per row. Writing it
// here rather than pulling in an image library keeps the suite dependency-free.

const CRC = (() => {
  const t = new Int32Array(256);
  for (let n = 0; n < 256; n++) {
    let c = n;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    t[n] = c;
  }
  return t;
})();

function crc32(buf) {
  let c = -1;
  for (let i = 0; i < buf.length; i++) c = CRC[(c ^ buf[i]) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([len, body, crc]);
}

function png(width, height_, rgb) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height_, 4);
  ihdr[8] = 8;        // bit depth
  ihdr[9] = 2;        // colour type: truecolour
  const raw = Buffer.alloc(height_ * (1 + width * 3));
  for (let y = 0; y < height_; y++) {
    const row = y * (1 + width * 3);
    raw[row] = 0;     // filter: none
    rgb.copy(raw, row + 1, y * width * 3, (y + 1) * width * 3);
  }
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', ihdr),
    chunk('IDAT', deflateSync(raw, { level: 6 })),
    chunk('IEND', Buffer.alloc(0))
  ]);
}

/** one terrarium tile of the fixture surface */
export function tilePng(z, x, y) {
  const b = tileBounds(x, y, z);
  const rgb = Buffer.alloc(SIZE * SIZE * 3);
  let k = 0;
  for (let j = 0; j < SIZE; j++) {
    const lat = b.n - ((j + 0.5) / SIZE) * (b.n - b.s);
    for (let i = 0; i < SIZE; i++) {
      const lng = b.w + ((i + 0.5) / SIZE) * (b.e - b.w);
      const v = Math.min(32767, Math.max(-32768, height(lng, lat))) + 32768;
      const r = Math.floor(v / 256);
      const g = Math.floor(v - r * 256);
      const bl = Math.floor((v - Math.floor(v)) * 256);
      rgb[k++] = r; rgb[k++] = g; rgb[k++] = bl;
    }
  }
  return png(SIZE, SIZE, rgb);
}
